name         'pipetomore-server_backup'
version      '0.1.0'
source       ''
author       'bairdt'
license      'Apache License, Version 2.0'
summary      'A module to configure basic tar based server backups for Linux servers'
description  'A module to configure basic tar based server backups for Linux servers'
project_page ''
